#ifndef INC_LCD_ILI9488_LCD_FONT_Rubik11x16
#define INC_LCD_ILI9488_LCD_FONT_Rubik11x16

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011
//http://www.mikroe.com
//
//GLCD FontName : Rubik-11
//GLCD FontSize : 11 x 16

extern const unsigned char Rubik11x16[];

#endif
