#ifndef INC_LCD_ILI9488_LCD_FONT_Unispace21x42
#define INC_LCD_ILI9488_LCD_FONT_Unispace21x42

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Unispace21x42
//GLCD FontSize : 21 x 42

extern const unsigned char Unispace21x42[];
        
#endif
