#ifndef INC_LCD_ILI9488_LCD_FONT_Unispace26x39
#define INC_LCD_ILI9488_LCD_FONT_Unispace26x39

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Unispace26x39
//GLCD FontSize : 26 x 39

extern const unsigned char Unispace26x39[];
        
#endif
        
