#ifndef INC_LCD_ILI9488_LCD_FONT_Arial28x28
#define INC_LCD_ILI9488_LCD_FONT_Arial28x28

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : @Arial_Unicode_MS28x28
//GLCD FontSize : 28 x 28

extern const unsigned char Arial28x28[];

#endif
