#ifndef INC_LCD_ILI9488_LCD_FONT_Arial24x23
#define INC_LCD_ILI9488_LCD_FONT_Arial24x23

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : @Arial_Unicode_MS24x23
//GLCD FontSize : 24 x 23

extern const unsigned char Arial24x23[];

#endif
