#ifndef INC_LCD_ILI9488_LCD_FONT_LCD55Mono37x48
#define INC_LCD_ILI9488_LCD_FONT_LCD55Mono37x48
//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : LCD-45 37x48
//GLCD FontSize : 37 x 48

extern const unsigned char LCD55Mono37x48[];
        
#endif
