#ifndef INC_LCD_ILI9488_LCD_FONT_OpenSansExtrabold31_42x46
#define INC_LCD_ILI9488_LCD_FONT_OpenSansExtrabold31_42x46

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : OpenSansExtrabold-31
//GLCD FontSize : 42 x 46

extern unsigned char OpenSansExtrabold31_42x46[];

#endif
