#ifndef INC_LCD_ILI9488_LCD_FONT_OpenSansExtrabold48_38x48_Digits
#define INC_LCD_ILI9488_LCD_FONT_OpenSansExtrabold48_38x48_Digits

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : OpenSansExtrabold-48 Digits Only
//GLCD FontSize : 38 x 48

extern const unsigned char OpenSansExtrabold48_38x48_Digits[];
        
#endif
