#ifndef INC_LCD_ILI9488_Arial20x23_RUS
#define INC_LCD_ILI9488_Arial20x23_RUS

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Arial-16 RUS
//GLCD FontSize : 20 x 23

extern const unsigned char Arial20x23_RUS[];

#endif
