#ifndef INC_LCD_ILI9488_LCD_FONT_Neu42x35
#define INC_LCD_ILI9488_LCD_FONT_Neu42x35

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Neu42x35
//GLCD FontSize : 42 x 35

extern const unsigned char Neu42x35[];
        
#endif
        
