#ifndef INC_LCD_ILI9488_LCD_FONT_Unispace32x48_Digits
#define INC_LCD_ILI9488_LCD_FONT_Unispace32x48_Digits

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Unispace-44 Digits Only
//GLCD FontSize : 32 x 48

extern const unsigned char Unispace32x48_Digits[];
        
#endif
