#ifndef INC_LCD_ILI9488_LCD_FONT_Digital7Mono32x48
#define INC_LCD_ILI9488_LCD_FONT_Digital7Mono32x48

//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektronika 2011 
//http://www.mikroe.com 

//GLCD FontName : Digital7Mono32x48
//GLCD FontSize : 32 x 48

extern const unsigned char Digital7Mono32x48[];
        
#endif
